resolvers:
  - 1.1.1.1
  - 1.0.0.1
  - 8.8.8.8
  - 8.8.4.4
  - 9.9.9.9
  - 9.9.9.10
  - 77.88.8.8
  - 77.88.8.1
  - 208.67.222.222
  - 208.67.220.220
sources:
  - alienvault
  - archiveis
  - binaryedge
  - bufferover
  - censys
  - certspotter
  - certspotterold
  - commoncrawl
  - crtsh
  - digicert
  - dnsdumpster
  - dnsdb
  - entrust
  - googleter
  - hackertarget
  - ipv4info
  - passivetotal
  - securitytrails
  - shodan
  - sitedossier
  - sublist3r
  - threatcrowd
  - threatminer
  - urlscan
  - virustotal
  - waybackarchive
  - zoomeye
binaryedge: []
censys: []
certspotter: []
dnsdb: []
passivetotal: []
securitytrails: []
shodan: []
urlscan: []
virustotal: []
zoomeye: []
